name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck and busted
        run: |
          luarocks install luacheck
          luarocks install busted

      - name: Luacheck
        run: luacheck .

      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

      - name: Run tests
        run: busted -v
